# Generated by Django 4.0.4 on 2022-11-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_category_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_data',
            old_name='description',
            new_name='descrpit',
        ),
    ]
